// =========================================================
// بيانات متجر خُيوط (Khyoot Store) — مسارات الصور الفعلية من public/images/products/
// =========================================================

export const tierLabels = {
  vip: { label: 'VIP', icon: '♛', className: 'tier-vip', color: 'var(--gold)' },
  premium: { label: 'بريميوم', icon: '◆', className: 'tier-premium', color: 'var(--emerald)' },
  classic: { label: 'كلاسيك', icon: '❖', className: 'tier-classic', color: 'var(--bronze)' },
};

export const products = [
  {
    id: 'kh-hoodie-quarter-zip', 
    name: 'هودي فاخر بنصف سحاب وقبعة وتفاصيل جلدية', 
    tier: 'vip', 
    swatch: 'gold', 
    price: 850, 
    originalPrice: 1100,
    badge: '♛ VIP حصري', 
    colors: ['عنابي', 'كحلي', 'بيج', 'أسود', 'أبيض', 'رمادي فاتح'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'هودي رجالي بياقة مرتفعة ونصف سحاب معدني صلب، مزود بأربطة قبعة عريضة بأطراف جلدية ومقبض سحاب متناسق. بطانة صوفية حرارية ناعمة لعزل حراري ممتاز.',
    fabric: '100% بوليستر عالي الكثافة معالج بتقنية Interlock', 
    images: ['/images/products/03232500802-A20M.jpg']
  },
  {
    id: 'kh-set-waffle-beige', 
    name: 'طقم قميص وسروال بيج نسيج وافل (قطعتين)', 
    tier: 'vip', 
    swatch: 'gold', 
    price: 1250, 
    originalPrice: 1500,
    badge: '♛ VIP طقم كامل', 
    colors: ['بيج نود'], 
    sizes: ['M','L','XL','XXL'],
    description: 'طقم صيفي/خريفي فاخر مكون من قميص بليزر بأزرار وجيوب صدر مع سروال مريح مصنع من نسيج الوافل القطني البارز ثلاثي الأبعاد لتهوية ممتازة.',
    fabric: 'قطن الوافل البارز (Waffle-Knit Cotton) عالي التهوية', 
    images: ['/images/products/03540525251-A20M.jpg']
  },
  {
    id: 'kh-sweater-brown-knit', 
    name: 'بلوفر تريكو صوفي بني مارل بياقة بولو', 
    tier: 'vip', 
    swatch: 'gold', 
    price: 890, 
    originalPrice: 1100,
    badge: '♛ VIP حصرية', 
    colors: ['بني موكا مارل'], 
    sizes: ['M','L','XL','XXL'],
    description: 'بلوفر كلاسيكي تريكو محبوك من ألياف الصوف الناعمة الدافئة بدرجة البني المارل الغني مع ياقة بولو بثلاثة أزرار وأكمام ملمومة.',
    fabric: 'تريكو صوفي مخلوط (Melange Wool Knit)', 
    images: ['/images/products/03665507803-A20M.jpg']
  },
  {
    id: 'kh-polo-knit-white', 
    name: 'قميص بولو تريكو صيفي محبوك أبيض', 
    tier: 'vip', 
    swatch: 'gold', 
    price: 680, 
    originalPrice: 820,
    badge: '♛ VIP', 
    colors: ['أبيض ناصع'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'قميص بولو صيفي محبوك من خيوط قطنية ناعمة، بتصميم أنيق ومريح مناسب للإطلالات اليومية.',
    fabric: '100% خيوط قطن ممشوط محبوكة', 
    images: ['/images/products/07210507403-A20M.jpg']
  },
  {
    id: 'kh-polo-ribbed-beige', 
    name: 'قميص بولو صيفي تريكو مضلع بيج رملي', 
    tier: 'vip', 
    swatch: 'gold', 
    price: 650, 
    originalPrice: 790,
    badge: '♛ VIP', 
    colors: ['بيج رملي'], 
    sizes: ['M','L','XL','XXL'],
    description: 'قميص بولو ناعم محبوك من التريكو المضلع طولياً بياقة مفرودة بدون أزرار ومظهر أنيق وفاخر.',
    fabric: 'تريكو ناعم عالي التهوية', 
    images: ['/images/products/07230933401-A20M.jpg']
  },
  {
    id: 'kh-coat-02', 
    name: 'معطف خيُوط الملكي الصوفي', 
    tier: 'vip', 
    swatch: 'gold', 
    price: 2400, 
    originalPrice: 2900,
    badge: '♛ VIP حصري', 
    colors: ['أسود ملكي','رمادي داكن'], 
    sizes: ['M','L','XL'],
    description: 'معطف شتوي بقوام أنيق، ببطانة داخلية ناعمة وتفاصيل عملية مناسبة للإطلالات الرسمية.',
    fabric: '80% صوف طبيعي معالج + 20% بوليستر', 
    images: ['/images/products/07232529250-A20M.jpg']
  },
  {
    id: 'kh-sweatpants', 
    name: 'بنطال جوجر ميلتون مبطن — تشكيلة 9 ألوان', 
    tier: 'premium', 
    swatch: 'emerald', 
    price: 550, 
    originalPrice: 700,
    badge: '◆ بريميوم', 
    colors: ['أسود','أبيض','أوف وايت','بني شوكولاتة','كحلي','أزرق ملكي','رمادي فاتح','زيتوني','رمادي داكن'], 
    sizes: ['M','L','XL','XXL','XXXL'],
    description: 'بنطال جوجر من خام الميلتون القطني الثقيل المبطن بظهر ناعم للدفء والراحة. حزام خصر مرن وأطراف مطاطية وتطريز جانبي ثابت.',
    fabric: '80% قطن طبيعي + 20% بوليستر (Anti-Pilling)', 
    images: ['/images/products/07660501427-A20M.jpg']
  },
  {
    id: 'kh-jeans-light-blue', 
    name: 'بنطال جينز كلاسيك بدرجة غسيل ثلجي فاتح', 
    tier: 'premium', 
    swatch: 'emerald', 
    price: 720, 
    originalPrice: 890,
    badge: '◆ بريميوم', 
    colors: ['أزرق ثلجي فاتح'], 
    sizes: ['30','31','32','33','34','36','38'],
    description: 'جينز كلاسيك معالج بالغسيل الحجري من القطن الثقيل مع خياطة نحاسية مزدوجة وأزرار معدنية.',
    fabric: '100% دنيم قطني ثقيل (Cotton Denim)', 
    images: ['/images/products/07660503434-A20M.jpg']
  },
  {
    id: 'kh-tank-polo-white', 
    name: 'تيشيرت كت بولو محبوك وافل أبيض', 
    tier: 'premium', 
    swatch: 'emerald', 
    price: 490, 
    originalPrice: 620,
    badge: '◆ بريميوم', 
    colors: ['أبيض ناصع'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'تيشيرت صيفي بدون أكمام بياقة بولو مفتوحة مصنع من نسيج الوافل المحبوك والبارز لتهوية عالية.',
    fabric: '100% قطن محبوك نسيج وافل', 
    images: ['/images/products/IMG-20260803-WA0023.jpg']
  },
  {
    id: 'kh-polo-retro-striped', 
    name: 'قميص بولو تريكو ريترو مقلم طولي', 
    tier: 'premium', 
    swatch: 'emerald', 
    price: 620, 
    originalPrice: 750,
    badge: '◆ بريميوم', 
    colors: ['أوف وايت مقلم بالنحاسي والزيتوني'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'بولو صيفي بياقة مفتوحة محبوك بتقليم طولي مدمج بالنحاسي والزيتوني لتهوية ممتازة وإطلالة ريترو.',
    fabric: '100% قطن مخرم ومحبوك (Open-Weave Cotton)', 
    images: ['/images/products/IMG-20260803-WA0024.jpg']
  },
  {
    id: 'kh-sweater-ribbed-white', 
    name: 'سويت شيرت تريكو ضلعي أبيض ناصع', 
    tier: 'premium', 
    swatch: 'emerald', 
    price: 580, 
    originalPrice: 720,
    badge: '◆ بريميوم', 
    colors: ['أبيض ناصع'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'سويت شيرت قطني بياقة دائرية ونقشة تريكو ضلعية طولية بارزة مع شعار معدني ناعم على الصدر.',
    fabric: 'تريكو مضلع (Rib-Knit Fabric) عالي المرونة', 
    images: ['/images/products/IMG-20260803-WA0025.jpg']
  },
  {
    id: 'kh-shorts-melton', 
    name: 'شورت ميلتون أوفرسايز بجيوب وخياطة طولية', 
    tier: 'classic', 
    swatch: 'bronze', 
    price: 380, 
    originalPrice: 480,
    badge: '❖ كلاسيك', 
    colors: ['رمادي فاتح مارل','أسود ملكي'], 
    sizes: ['M','L','XL','XXL'],
    description: 'شورت صيفي مريح من خام الميلتون القطني مع حزام خصر مرن برباط تعديل وخياطة أمامية طولية وجيب خلفي.',
    fabric: 'ميلتون قطني صيفي ناعم وبدون تبطين حراري', 
    images: ['/images/products/IMG-20260803-WA0026.jpg']
  },
  {
    id: 'kh-tee-stwd', 
    name: 'تيشيرت أوفرسايز جرافيك STWD فحمي', 
    tier: 'classic', 
    swatch: 'bronze', 
    price: 450, 
    originalPrice: 550,
    badge: '❖ كلاسيك', 
    colors: ['رمادي فحمي'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'تيشيرت أوفرسايز رمادي فحمي بأكتاف مائلة وطباعة جرافيكية، مناسب للإطلالات الكاجوال.',
    fabric: '100% قطن ثقيل بكثافة 220 غرام/م²', 
    images: ['/images/products/IMG-20260803-WA0027.jpg']
  },
  {
    id: 'kh-tee-summer-white', 
    name: 'تيشيرت أوفرسايز أبيض جرافيك SUMMER RHYTHMS', 
    tier: 'classic', 
    swatch: 'bronze', 
    price: 440, 
    originalPrice: 540,
    badge: '❖ كلاسيك', 
    colors: ['أبيض ناصع'], 
    sizes: ['S','M','L','XL','XXL'],
    description: 'تيشيرت أوفرسايز قطن أبيض نقي بطباعة صيفية أمامية وخلفية، مناسب للإطلالات اليومية.',
    fabric: '100% قطن ثقيل عالي الجودة', 
    images: ['/images/products/IMG-20260803-WA0028.jpg']
  }
];

export const categories = ['الكل', 'VIP', 'بريميوم', 'كلاسيك'];
